### ISSUE TITLE
BUG: przelewy24 will give error

### ISSUE THREAD

**Issue by henkvalk** [Siteation/magento2-hyva-icons-payment#7]
The icon przelewy24 will show an error, because it will be transformed to przelewy-24. 

Please rename `przelewy24.svg` to `przelewy-24.svg`

**Comment by GrimLink** [comment]
Thanks @henkvalk for reporting this, on it 😉

**Comment by GrimLink** [comment]
@henkvalk I can not reproduce this issue, if I change the name to `przelewy-24.svg` I get an error.

What version of Hyva are your using?
